student:
  arch: vit_large
  patch_size: 16 
  drop_path_rate: 0   
  layerscale: 1.0e-05
  drop_path_uniform: true
  ffn_layer: swiglufused
  block_chunks: 4
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1